### ISSUE TITLE
determinism of test

### ISSUE THREAD

**Issue by scivision** [ec500-software-engineering/exercise-2-ffmpeg-ethanhou99#1]
* the test should ensure that the conversion runs, not by using time.sleep
* this can be done via pytest.fixture, or just by calling your conversion function before the file comparison test

**Comment by ethanhou99** [comment]
Yes, I deleted the time.sleep() function. Actually that was because the CI server always report weirdo errors, since the code can run successfully in my own laptop. The error has already been fixed. Actually if you remember, you helped me changed the ffmpeg command and I change input and output files to .avi as well. Finally it works.
